version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: docker-registry
  hooks:
    - type: mail
      disabled: true
      levels:
        - panic
      options:
        smtp:
          addr: mail.163.com:25
          username: mailuser
          password: password
          insecure: true
        from: yit-ci@yit.com
        to:
          - tatumsu@163.com
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
storage:
  oss:
    accesskeyid: gxAzbBXdd0DNhVQc
    accesskeysecret: 5JCc6PDVZ72ArdLM2VpNRmoQxExUKO
    region: oss-us-west-1
    internal: true
    bucket: tatum-docker-registry
    rootdirectory: 
  delete:
    enabled: false
  redirect:
    disable: false
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: false
      age: 168h	
      interval: 24h
      dryrun: false
http:
  addr: 0.0.0.0:5000
  debug:  
    addr: 0.0.0.0:5001
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 5m
    threshold: 6 
